version: '3.7'
services:
  jenkins:
    build:
      context: .
      dockerfile: jenkins.Dockerfile
    ports:
      - 8182:8080
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
      - $PWD/website:/app

